version: '3'

networks:
  chatbot-network:
    driver: bridge

services:

  chatbot:
    image: ${DOCKER_MAIN_IMAGE}
    container_name: chatbot
    depends_on:
      - db
    ports:
      - '8000:8080'
    env_file:
      - ./.env
    networks:
      - chatbot-network
    volumes:
      - static:/static
      - ./:/usr/src/app

  nginx: 
    build: ./nginx
    container_name: nginx
    volumes:
      - static:/static
    ports:
      - '80:80'
    depends_on:
      - chatbot
    networks:
      - chatbot-network

  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - chatbot-network

volumes:
  static:
  db:
    driver: local