version: '3'


services:
  # api:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - '8000:8080'
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./:/usr/src/app:ro
  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data

  db_test:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}_test
    ports:
      - '${POSTGRES_PORT_TESTING}:5432'
volumes:
  db:
    driver: local