version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=rental_system
      - POSTGRES_PASSWORD=postgres
    ports:
      - '7878:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
