version: '3'
services:
  # api:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - '8000:8080'
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./:/usr/src/app:ro
  db:
    image: postgres
    container_name: postgres
    restart: always
    # environment:
    #   - POSTGRES_USER=rental_system
    #   - POSTGRES_PASSWORD=postgres
      
    env_file:
      - ./.env
      - - POSTGRES_DB = $POSTGRES_DB_TESTING
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local