name: Build and Deploy

on:
  push:
    branches:
      - "master"
jobs:
  Continious_Integration:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: installing python version 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installing all the dependency
        run: pip install -r requirements.txt
      - name: dockerizing backend app
        run: sudo docker build -t mihirshah01/rental_system .
      - name: pushing image to dockerhub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PWD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          sudo docker login -u $DOCKER_USER -p $DOCKER_PWD
          sudo docker push $DOCKER_USER/rental_system:backend_api
      - name: docker logout
        run: sudo docker logout
  Continious_Deployment: 
    needs: [Continious_Integration]
    runs-on: ubuntu-latest
      steps:
        name: deployment
